modelClass: Cms\Models\Component
form: $/firstwave/workproject/models/componenttype/fields.yaml
title: Components
fields:
    name:
        label: Name
        type: text
        span: left
    component_type:
        label: Type
        type: dropdown
        span: right
        options: Cms\Models\Component::getComponentTypeOptions
    page:
        label: Page
        type: relation
        span: left
        placeholder: Select a page
    order:
        label: Order
        type: number
        span: right
        default: 0
    sort_order:
        label: Sort Order
        type: number
        span: left
        default: 0
    deleted:
        label: Deleted
        type: checkbox
        span: right
        default: 0
    description:
        label: Description
        type: textarea
        span: full
tabs:
    fields:
        # Define tabs if needed
toolbar:
    buttons:
        save:
            label: Save
            class: primary
        saveAndClose:
            label: Save & Close
        cancel:
            label: Cancel
